policies:
- name: require-non-root-group
  labels:
    adrp.xyz/kyverno: security
  annotations:
    policies.kyverno.io/title: Reqire Non-root Group
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Following the least privilege principle, access to the root group ID should be forbidden
      in containers. This policy ensures containers are running with groups > 0.
  spec:
    validationFailureAction: Enforce
    rules:
    - name: run-as-group
      match:
        all:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          runAsGroup must be set to an id > 0 in either spec.securityContext.runAsGroup or spec.containers[*].securityContext.runAsGroup
        foreach:
        - list: request.object.spec.containers[]
          pattern:
            =(securityContext):
              =(runAsGroup): "*"
