---
apiVersion: v1
kind: Service
metadata:
  name: {{printf "%s-%s" (include "standardnotes.fullname" .) .Values.sync.name | trunc 63 | trimSuffix "-"}}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "standardnotes.labels" . | nindent 4}}
spec:
  ports:
  - protocol: TCP
    name: sync
    port: {{.Values.sync.port}}
    targetPort: {{.Values.sync.port}}
  clusterIP: None
  selector:
    {{- include "standardnotes.syncSelectorLabels" . | nindent 4}}
