{{- if and (dig "network" "policies" true .Values.package) (dig "network" "allowDnsEgress" true .Values.package) -}}
{{- $pkg := .Values.package -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "resourceName" (printf "%s-dns" .Values.package.name) }}
  namespace: {{ default $pkg.name $pkg.namespace.name }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
{{- end -}}
