{{- if and (dig "network" "policies" true .Values.package) (dig "network" "allowIngress" true .Values.package) -}}
{{- range $host := .Values.package.network.allowIngress -}}
{{- $namespace := $host.namespaceSelctor | required "namespaceSelctor is required." }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "resourceName" (printf "%s-ingress-%s" $.Values.package.name $host.name) }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  {{- if $host.podSelector}}
  podSelector:
    matchLabels:
      {{- toYaml $host.podSelector | nindent 6 }}
  {{- end }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{-  toYaml $namespace | nindent 10 }}
      {{- if $host.ingressPodSelector }}
      podSelector:
        matchLabels:
          {{-  toYaml $host.ingressPodSelector | nindent 10 }}
      {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          {{-  toYaml $namespace | nindent 10 }}
      {{- if $host.ingressPodSelector }}
      podSelector:
        matchLabels:
          {{-  toYaml $host.ingressPodSelector | nindent 10 }}
      {{- end -}}
{{ end -}}
{{- end -}}
