{{- /* Adds additional policies based on values */ -}}
{{- if and (dig "network" "policies" true .Values.package) (dig "additionalPolicies" false .Values.package.network) -}}
{{- $pkg := .Values.package -}}
{{- range $policy := .Values.package.network.additionalPolicies -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $policy.name }}
  namespace: {{ default $pkg.name $pkg.namespace.name }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  {{- toYaml $policy.spec | nindent 2 }}
{{- end -}}
{{- end -}}
