{{- if not .Values.package.name -}}
{{ fail "Package needs a name, include '.package.name' " }}
{{- end }}
{{- $pkg := .Values.package -}}
{{- if $pkg.values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pkg.name }}-values
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
    {{- if (dig "namespace" "labels" nil $pkg) -}}
    {{- toYaml $pkg.namespace.labels | nindent 4 -}}
    {{- end -}}
  {{- if (dig "namespace" "annotations" nil $pkg) }}
  annotations:
    {{- toYaml $pkg.namespace.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
stringData:
  values.yaml: |
  {{- tpl (toYaml $pkg.values) $ | nindent 4 }}
{{- end }}
