---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ printf "%s-%s" (include "standardnotes.name" .) .Values.auth.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "standardnotes.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ include "standardnotes.serviceAccountName" . }}
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "standardnotes.authWorkerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "standardnotes.authWorkerSelectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ printf "%s" .Values.auth.name | trunc 63 | trimSuffix "-" }}
        image: {{ printf "%s:%s" .Values.auth.image.repository (default "latest" .Values.auth.image.tag) | quote}}
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        command:
        - ./docker/entrypoint.sh
        args:
        - start-worker
        env:
        - name: PORT
          value: {{ .Values.auth.port }}
        - name: AUTH_SERVER_URL
          // TODO: Move this SVC name generator too _helpers.tpl
          value: {{ printf "http://%s:%d" (printf "%s-%s" (include "standardnotes.name" .) .Values.auth.name | trunc 63 | trimSuffix "-") (.Values.auth.port | int) }}
        {{- with .Values.auth.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with (default .Values.global.livenessProbe .Values.auth.livenessProbe) }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with (default .Values.global.resources .Values.auth.resources) }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
