---
apiVersion: v2
appVersion: v0.10.7
description: Dendrite Matrix Homeserver
name: dendrite
version: 9.1.23
kubeVersion: ">=1.20.0-0"
deprecated: true
keywords:
- dendrite
- matrix
- homeserver
- monolith
- federation
- polylith
home: https://github.com/a1994sc/helm/tree/main/charts/dendrite
sources:
- https://github.com/matrix-org/dendrite
- https://github.com/matrix-org/dendrite/tree/master/build/docker
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
- name: nats
  version: 1.3.2
  repository: https://nats-io.github.io/k8s/helm/charts/
  condition: nats.enabled
# Client API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: clientapi
  condition: dendrite.polylithEnabled
# Media API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: mediaapi
  condition: dendrite.polylithEnabled
# Sync API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: syncapi
  condition: dendrite.polylithEnabled
# Room Server
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: roomserver
  condition: dendrite.polylithEnabled
# Federation API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: federationapi
  condition: dendrite.polylithEnabled
# Key Server
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: keyserver
  condition: dendrite.polylithEnabled
# User API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: userapi
  condition: dendrite.polylithEnabled
# App Service API
- name: common
  repository: https://bjw-s.github.io/helm-charts/
  version: 3.7.3
  alias: appserviceapi
  condition: dendrite.polylithEnabled
annotations:
  org.opencontainers.image.source: https://github.com/A1994SC/helm
