apiVersion: v2
name: packager
version: 1.1.1
description: Allows bundling of supporting charts
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
type: application
annotations:
  org.opencontainers.image.source: https://github.com/A1994SC/helm
