domain: ""

helmRepositories: []
# - name: "ghcr-io"
#   repository: "oci://ghcr.io/a1994sc/helm"
#   existingSecret: "private-registry"
#   type: "oci"
#   username: ""
#   password: ""
#   email: ""

# -- (Advanced) Flux reconciliation parameters.
# The default values provided will be sufficient for the majority of workloads.
flux:
  timeout: 10m
  interval: 2m
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: true


# -- Wrapper chart for integrating common additions to charts
wrapper:
  # -- Choose source type of "git" or "helmRepo"
  sourceType: "helmRepo"

  helmRepo:
    # -- Repository holding OCI chart, corresponding to `helmRepositories` name
    repoName: "ghcr-io"
    # -- Name of the OCI chart in `repo`
    chartName: wrapper
    # -- Tag of the OCI chart in `repo`
    tag: "1.0.5"

packages:
  sample:
    # -- Toggle deployment of this package
    # @default -- true
    enabled: false

    # @default -- false
    wrapper:
      enabled: true

    # -- HelmRepo source is supported as an option for Helm deployments. If both `git` and `helmRepo` are provided `helmRepo` will take precedence.
    helmRepo:
      # -- Name of the HelmRepo specified in `helmRepositories`
      # @default -- Uses `ghcr-io` Helm Repository if not specified
      repoName:
      # -- Name of the chart stored in the Helm repository
      # @default -- Uses values key/package name if not specified
      chartName:
      # -- Tag of the chart in the Helm repo, required
      tag:

      # -- Git source is supported for both Helm and Kustomize deployments. If both `git` and `helmRepo` are provided `helmRepo` will take precedence.
    git:
      # -- Git repo URL holding the helm chart for this package, required if using git
      repo:
      # -- Git commit to check out.  Takes precedence over semver, tag, and branch. [More info](https://fluxcd.io/flux/components/source/gitrepositories/#reference)
      commit:
      # -- Git semVer tag expression to check out.  Takes precedence over tag. [More info](https://fluxcd.io/flux/components/source/gitrepositories/#reference)
      semver:
      # -- Git tag to check out.  Takes precedence over branch. [More info](https://fluxcd.io/flux/components/source/gitrepositories/#reference)
      tag:
      # -- Git branch to check out.  [More info](https://fluxcd.io/flux/components/source/gitrepositories/#reference).
      # @default -- When no other reference is specified, `master` branch is used
      branch:
      # -- Path inside of the git repo to find the helm chart or kustomize
      # @default -- For Helm charts `chart`.  For Kustomize `/`.
      path:

    # -- Override flux settings for this package
    flux: {}

    # FluxCD Helm Release Post Renders
    postRenderers: []

    # FluxCD Helm Release Dependacy
    dependsOn: []

    # Wrapper options that are passed down to the wrapper chart.
    network: {}
    ingress: {}
    certificate: {}
    secrets: []
    configMaps: []
