
{{- $pkg := .Values.package -}}
{{- range $i, $cert := $pkg.certificate.certs -}}
{{- if and (not $cert.dnsNames) (not $cert.ipAddresses) }}
{{- fail (printf "Values for certificate SAN (dnsNames or ipAddresses) are required for package.certificate.certs.%d" $i) }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A name is required for each certificate" $cert.name }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  secretName: {{ required "A name for the secret is required for each certificate" $cert.secretName }}
  privateKey:
    rotationPolicy: Always
  {{- $issuer := $cert.issuerRef | required (printf "package.certificate.certs.%d.issuerRef is required." $i) }}
  issuerRef:
  {{- toYaml $issuer | nindent 4}}
  {{- if $cert.dnsNames }}
  dnsNames:
  {{- tpl (toYaml $cert.dnsNames) $ | nindent 2}}
  {{- end }}
  {{- if $cert.ipAddresses }}
  ipAddresses:
  {{- toYaml $cert.ipAddresses | nindent 2}}
  {{- end }}
{{ end -}}
