{{- if not (or (eq .Values.package.network.backend "native") (eq .Values.package.network.backend "cilium")) }}
{{- fail "The only supported backends for network policies is 'native' or 'cilium'" }}
{{- end }}

{{- /* Adds additional policies based on values */ -}}
{{- if eq (dig "network" "backend" "native" .Values.package) "native" }}
{{- if and (dig "network" "policies" true .Values.package) (dig "additionalPolicies" false .Values.package.network) -}}
{{- range $policy := .Values.package.network.additionalPolicies -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $policy.name }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  {{- toYaml $policy.spec | nindent 2 }}
{{ end -}}
{{- end -}}
{{- end -}}
