{{- if eq (dig "network" "backend" "native" .Values.package) "native" }}
{{- if and (dig "network" "policies" true .Values.package) (dig "network" "allowControlPlaneEgress" false .Values.package) -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "resourceName" (printf "%s-controlplane" .Values.package.name) }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.package.network.controlPlaneCidr }}
        {{- if eq .Values.package.network.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
{{- end -}}
{{- end -}}
