{{- if eq (dig "network" "backend" "native" .Values.package) "native" }}
{{- if and (dig "network" "policies" true .Values.package) (dig "network" "allowIntraNamespace" true .Values.package) -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "resourceName" (printf "%s-intranamespace" .Values.package.name) }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
{{- end -}}
{{- end -}}
