---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "standardnotes.name" .) .Values.auth.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "standardnotes.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      name: auth
      port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
  clusterIP: None
  selector:
    {{- include "standardnotes.authSelectorLabels" . | nindent 4 }}
