{{- /* Adds additional policies based on values */ -}}
{{- if eq (dig "network" "backend" "native" .Values.package) "cilium" }}
{{- if and (dig "network" "policies" true .Values.package) (dig "additionalPolicies" false .Values.package.network) -}}
{{- range $policy := .Values.package.network.additionalPolicies -}}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ $policy.name }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  {{- toYaml $policy.spec | nindent 2 }}
{{ end -}}
{{- end -}}
{{- end -}}
