{{- if eq (dig "network" "backend" "native" .Values.package) "cilium" }}
{{- if and (dig "network" "policies" true .Values.package) (dig "network" "allowControlPlaneEgress" false .Values.package) -}}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "resourceName" (printf "%s-controlplane" .Values.package.name) }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "443"
      - port: "6443"
{{- end -}}
{{- end -}}
