apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-pipeline.fullname" . }}-bundleresolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipeline.labels" . | nindent 4 }}
data:
  default-kind: {{ .Values.bundleresolverConfig.defaultKind | quote }}
