apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-pipeline.fullname" . }}-config-registry-cert
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipeline.labels" . | nindent 4 }}
