apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-pipeline.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipeline.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-pipeline.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipeline.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}
