---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{printf "%s-%s" (include "standardnotes.fullname" .) .Values.file.name | trunc 63 | trimSuffix "-"}}
  namespace: {{.Release.Namespace}}
  labels:
    {{include "standardnotes.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "standardnotes.fileSelectorLabels" . | nindent 6}}
  serviceName: {{printf "%s-%s" (include "standardnotes.fullname" .) .Values.file.name | trunc 63 | trimSuffix "-"}}
  minReadySeconds: {{default .Values.global.minReadySeconds .Values.file.minReadySeconds}}
  template:
    metadata:
      {{- with .Values.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      labels:
        {{- include "standardnotes.fileSelectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{include "standardnotes.serviceAccountName" .}}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{printf "%s" .Values.file.name | trunc 63 | trimSuffix "-"}}
        image: {{printf "%s:%s" .Values.file.image.repository (default "latest" .Values.file.image.tag) | quote}}
        imagePullPolicy: {{.Values.file.image.pullPolicy}}
        env:
          - name: PORT
            {{printf "value: %s" (.Values.file.port | quote)}}
          - name: REDIS_EVENTS_CHANNEL
            {{printf "value: %s" (.Values.file.redisChannel | quote)}}
          {{- if .Values.global.env}}
          {{- range $i, $val := .Values.global.env}}
          - name: {{$val.name}}
            {{printf "value: %s" ($val.value | quote)}}
          {{- end}}
          {{- end}}
          {{- if .Values.file.env}}
          {{- range $i, $val := .Values.file.env}}
          - name: {{- $val.name}}
            {{printf "value: %s" ($val.value | quote)}}
          {{- end}}
          {{- end}}
        {{- with .Values.file.envFrom}}
        envFrom:
          {{- toYaml . | nindent 10}}
        {{- end}}
        {{- with (default .Values.global.livenessProbe .Values.file.livenessProbe)}}
        livenessProbe:
          {{- toYaml . | nindent 10}}
        {{- end}}
        {{- with (default .Values.global.resources .Values.file.resources)}}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end}}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.global.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.global.affinity}}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.global.tolerations}}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}
