---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ksca.fullname" . }}
  labels:
    {{- include "ksca.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "ksca.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ksca.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cert-approver
        args:
        - serve
        {{- if gt (.Values.replica | int) 1 }}
        - --enable-leader-election
        {{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 6
        ports:
        - containerPort: 8080
          name: health
        {{- if .Values.metrics.enabled }}
        - containerPort: 9090
          name: metrics
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- with .Values.extraVolumes.volumeMounts }}
        volumeMounts:
        {{ toYaml . | nindent 8 | trim }}
        {{- end }}
      priorityClassName: system-cluster-critical
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "ksca.serviceAccountName" . }}
      {{- with .Values.extraVolumes.volumes }}
      volumes:
      {{ toYaml . | nindent 6 | trim }}
      {{- end }}
