{{ if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: kubelet-serving-cert-approver
  labels:
    {{- include "ksca.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "ksca.selectorLabels" . | nindent 4 }}
{{ end }}
