apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  name: {{ include "tekton-trigger-interceptor.fullname" . }}-lab
  labels:
    server/type: https
  {{- include "tekton-trigger-interceptor.labels" . | nindent 4 }}
spec:
  clientConfig:
    service:
      name: tekton-triggers-core-interceptors
      namespace: tekton-pipelines
      path: gitlab
      port: 8443
