apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-trigger-interceptor.fullname" . }}-tekton-triggers-core-interceptors
  labels:
    app: tekton-triggers-core-interceptors
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.25.3
    version: v0.25.3
  {{- include "tekton-trigger-interceptor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tektonTriggersCoreInterceptors.type }}
  selector:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: core-interceptors
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-trigger-interceptor.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.tektonTriggersCoreInterceptors.ports | toYaml | nindent 2 -}}
