apiVersion: v2
name: wrapper
version: 1.2.3
description: Adds extra supporting packages
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
type: application
annotations:
  org.opencontainers.image.source: https://github.com/A1994SC/helm
