---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: events:kubelet-serving-cert-approver
  labels:
    {{- include "ksca.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
