---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events:kubelet-serving-cert-approver
  namespace: default
  labels:
    {{- include "ksca.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: events:kubelet-serving-cert-approver
subjects:
- kind: ServiceAccount
  name: {{ include "ksca.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
