{{- if gt (.Values.replica | int) 1 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election:kubelet-serving-cert-approver
  labels:
    {{- include "ksca.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
{{ end -}}
