{{- $gateway := .Values.package.entry.gateway }}
{{- if and (dig "entry" "gateway" "hosts" false .Values.package) $gateway.enabled }}
{{- range $host := $gateway.hosts }}
{{- range $listen := $host.listeners }}
{{- if (or (eq $listen.protocol "HTTPS") (eq $listen.protocol "HTTP")) }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "resourceName" (printf "%s-%s-%s" $.Values.package.name $host.name $listen.name) }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
    {{- if $gateway.labels }}
    {{- toYaml $gateway.labels | nindent 4 }}
    {{- end }}
    {{- if $host.labels }}
    {{- toYaml $host.labels | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ include "resourceName" (printf "%s-%s-%s" $.Values.package.name $host.name (default $.Values.domain $host.domain)) }}
    sectionName: {{ $listen.name }}
  hostnames:
  - {{ printf "%s.%s" (default $host.name $listen.hostname) (default $.Values.domain $host.domain) | quote }}
  rules:
  {{- range $rule := $listen.rules }}
  {{- toYaml (list $rule) | nindent 2 }}
  {{- if not $rule.matches }}
    matches:
    - path:
        type: PathPrefix
        value: /
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
