apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-trigger.fullname" . }}-controller
  labels:
    app: tekton-triggers-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.25.3
    version: v0.25.3
  {{- include "tekton-trigger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.type }}
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-trigger.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.controller.ports | toYaml | nindent 2 -}}
