{{- $gateway := .Values.package.entry.gateway }}
{{- if and (dig "entry" "gateway" "hosts" false .Values.package) $gateway.enabled }}
{{- range $host := $gateway.hosts }}
{{- range $listen := $host.listeners }}
{{- if (and (dig "extra" "httpRedirct" false $listen) (eq $listen.protocol "HTTPS")) }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "resourceName" (printf "https-redirect-%s-%s-%s" $.Values.package.name $host.name $listen.name) }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
    {{- if $gateway.labels }}
    {{- toYaml $gateway.labels | nindent 4 }}
    {{- end }}
    {{- if $host.labels }}
    {{- toYaml $host.labels | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ include "resourceName" (printf "%s-%s-%s" $.Values.package.name $host.name (default $.Values.domain $host.domain)) }}
    sectionName: http-redirect
  hostnames:
  - {{ printf "%s.%s" (default $host.name $listen.hostname) (default $.Values.domain $host.domain) | quote }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: {{ $listen.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
