{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) (dig "wrapper" "enabled" false $vals) -}}
{{- $pkg = include "resourceName" $pkg -}}
{{- $fluxSettings := merge (dig "flux" dict $vals) $.Values.flux -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $pkg }}-wrapper
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}-wrapper
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  releaseName: {{ $pkg }}-wrapper
  chart:
    spec:
      {{- if (eq $.Values.wrapper.sourceType "helmRepo") }}
      chart: {{ $.Values.wrapper.helmRepo.chartName }}
      version: {{ $.Values.wrapper.helmRepo.tag | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ $.Values.wrapper.helmRepo.repoName }}
        namespace: {{ dig "wrapper" "helmRepo" "namespace" "flux-system" $vals }}
      {{- else }}
      chart: {{ default "chart" $.Values.wrapper.git.path }}
      sourceRef:
        kind: GitRepository
        name: {{ $.Release.Name }}-wrapper
        namespace: {{ $.Release.Namespace }}
      {{- end }}
      interval: {{ default "5m" $fluxSettings.interval }}
      reconcileStrategy: Revision
  {{- toYaml $fluxSettings | nindent 2 }}
  valuesFrom:
    - name: {{ $pkg }}-wrapper-values
      kind: Secret
{{ end -}}
{{- end -}}
