name: Release Charts

on:
  push:
    branches:
    - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: helm-release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.11.3

    - name: Add repositories
      run: |
        for dir in $(ls -d charts/*/); do
          helm dependency list $dir 2> /dev/null | head -n -1 | grep -v "NAME" | awk -v env_dir="$(basename $dir)" '{ print "helm repo add " env_dir "-" $1 " " $3  }' | sort | uniq | grep -i "http" | while read cmd; do $cmd; done
        done

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      env:
        CR_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        CR_SKIP_EXISTING: true

    - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        charts_dir: charts
        charts_url: https://a1994sc.github.io/helm
        owner: a1994sc
        repository: helm
        branch: gh-pages
